name: Trigger Docs Site Build

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'  # Only trigger when files in the docs directory change
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs.mecattaf.dev build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          repository: mecattaf/docs.mecattaf.dev
          event-type: content_update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
